-- DC-005: categorías aditivas de Document (MySQL ENUM MODIFY)
ALTER TABLE `Document` MODIFY COLUMN `category` ENUM(
  'IDENTITY',
  'PROOF_OF_ADDRESS',
  'SSN_DOCUMENT',
  'CREDIT_REPORT',
  'DISPUTE_LETTER',
  'UPDATE_REPORT',
  'PAYMENT_PROOF',
  'CONTRACT',
  'INVOICE',
  'RECEIPT',
  'BANK_DOCUMENT',
  'BUSINESS_DOCUMENT',
  'OTHER'
) NOT NULL;
