-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('TASK_DUE', 'TASK_OVERDUE', 'CASE_REVIEW_DUE', 'ROUND_REVIEW_DUE', 'PAYMENT_DUE', 'SYSTEM', 'DAILY_DIGEST', 'MAIL_RECEIVED', 'CONTACT_FORM') NOT NULL;

-- AlterTable
ALTER TABLE `OrganizationSettings`
  ADD COLUMN `notifyEmailContact` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `notifyWhatsappContact` BOOLEAN NOT NULL DEFAULT true;
